sudo: required
dist: trusty
language: go
services:
  - docker

go:
  - 1.14

install:
- sudo docker version
- sudo pip install docker-compose
- docker-compose version

before_script:
- docker-compose -f $TRAVIS_BUILD_DIR/test-dependencies.yml up -d
- sleep 15

script:
- make test
